version: '2'
services:
  sisito:
    build: .
    ports:
     - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: 'mysql:5.6'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
