admin:
  username: admin
  password: pass
  #secret_file: path_to_yaml
authz:
  disable_mask: false
  show_whitelist: true
  show_admin: false
smtp:
  foo@example.com:
    address: localhost
    port: 25
    enable_starttls_auto: false
digest: sha1
#mail_link: "https://localhost:9200/_plugin/kibana/#/discover?_a=(index:'maillog-*',query:(query_string:(query:'digest:%{digest}')))"
header_links:
  "Example Domain": http://example.com/
  "Bounce Reason": http://libsisimai.org/en/reason/
#shorten_stats: false
#bounce_over:
#  buffer: 0
#omniauth:
#  google_client_id: ~
#  google_client_secret: ~
#  hd:
#    - example.com
#  allow_users:
#    - foo@example.com
#    - bar@example.com
