admin:
  username: admin
  password: pass
whitelist_auth: true
smtp:
  foo@example.com:
    address: localhost
    port: 25
    enable_starttls_auto: false
digest: sha1
#mail_link: "https://localhost:9200/_plugin/kibana/#/discover?_a=(index:'maillog-*',query:(query_string:(query:'digest:%{digest}')))"
header_links:
  "Example Domain": http://example.com/
#bounce_over:
#  buffer: 0
#omniauth:
#  google_client_id: ~
#  google_client_secret: ~
